const router = require('express').Router();
const { PrismaClient } = require('@prisma/client');
const multer = require('multer');
const path = require('path');
const authMiddleware = require('../middleware/auth');
const { uploadFile, getSignedUrl, deleteFile } = require('../services/storageService');

const prisma = new PrismaClient();

// Multer config (memory storage for processing before local save)
const upload = multer({
    storage: multer.memoryStorage(),
    limits: { fileSize: 50 * 1024 * 1024 }, // 50MB
    fileFilter: (req, file, cb) => {
        const allowed = ['.pdf', '.jpg', '.jpeg', '.png', '.gif', '.doc', '.docx', '.txt', '.webm', '.mp4'];
        const ext = path.extname(file.originalname).toLowerCase();
        if (allowed.includes(ext)) {
            cb(null, true);
        } else {
            cb(new Error('File type not allowed'));
        }
    },
});

// Helper to ensure a folder exists
async function ensureFolder(name, parentId, courseId, ownerId) {
    // For root course folders (parentId is null), look up strictly by courseId
    const query = (parentId === null && courseId)
        ? { parentId: null, courseId }
        : { name, parentId, courseId };

    let folder = await prisma.folder.findFirst({
        where: query
    });

    if (!folder) {
        // Get parent path
        let parentPath = '';
        if (parentId) {
            const parent = await prisma.folder.findUnique({ where: { id: parentId } });
            if (parent) parentPath = parent.path;
        }

        folder = await prisma.folder.create({
            data: {
                name,
                path: parentPath ? `${parentPath}/${name}` : (courseId ? `/courses/${courseId}/${name}` : name),
                ownerId,
                parentId,
                courseId,
                isAutoGenerated: true
            }
        });
    }
    return folder;
}

// POST /api/documents/upload
router.post('/upload', authMiddleware, upload.single('file'), async (req, res) => {
    try {
        if (!req.file) {
            return res.status(400).json({ error: 'No file uploaded' });
        }

        // Sanitize helper
        // Optionally pass a flag to strip specific suffixes like ' - Modified'
        const sanitize = (str, isCourseName = false) => {
            let s = str || '';
            if (isCourseName) {
                // Strip " - Modified" (case-insensitive) before sanitizing
                s = s.replace(/\s*-\s*Modified\s*/gi, '');
            }
            return s.replace(/[^a-zA-Z0-9._-]/g, '_');
        };

        const { courseId, sessionId, folderId, type, source } = req.body;
        const timestamp = Date.now();
        const safeName = `${timestamp}_${sanitize(req.file.originalname)}`;

        let finalFolderId = folderId;

        // Fix: Handle Virtual Folder IDs from Frontend (e.g., 'private', 'students', 'virtual_...')
        // If folderId is not a valid UUID, set it to null (Root)
        const isUuid = (id) => /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i.test(id);
        if (finalFolderId && !isUuid(finalFolderId)) {
            console.log(`[Upload] Virtual folderId detected: ${finalFolderId}. Mapping to NULL.`);
            finalFolderId = null;
        }

        let ownerId = req.user.id; // Uploader

        // Fix: Inherit courseId from folder if not provided by frontend
        let activeCourseId = courseId;
        if (!activeCourseId && finalFolderId) {
            const folderInfo = await prisma.folder.findUnique({ where: { id: finalFolderId } });
            if (folderInfo && folderInfo.courseId) {
                activeCourseId = folderInfo.courseId;
            }
        }

        // ---------------------------------------------------------
        // 1. Auto-Archiving Logic (Virtual Structure Creation)
        // ---------------------------------------------------------
        if (activeCourseId && (source === 'chat_attachment' || source === 'screenshot')) {
            const course = await prisma.course.findUnique({ where: { id: activeCourseId } });
            if (course) {
                const structOwnerId = course.professorId;
                // Ensure Hierarchy: Course -> Archives -> Date
                const rootFolder = await ensureFolder(course.title, null, activeCourseId, structOwnerId);
                const archivesFolder = await ensureFolder('Archives', rootFolder.id, activeCourseId, structOwnerId);
                const dateStr = new Date().toISOString().split('T')[0];
                const dateFolder = await ensureFolder(dateStr, archivesFolder.id, activeCourseId, structOwnerId);
                finalFolderId = dateFolder.id;
            }
        }

        // ---------------------------------------------------------
        // 2. Physical Path Construction (New Structure)
        // Pattern: 
        //   - Private: Teacher_{ID}/Private/{VirtualPath}/{Filename}
        //   - Course:  Teacher_{ID}/Student/{CourseName}/{Filename}
        // ---------------------------------------------------------

        let targetPath = '';
        let targetFolderIds = []; // To build path string if needed

        // Resolve Root Context
        if (activeCourseId) {
            // --- COURSE CONTEXT ---
            const course = await prisma.course.findUnique({
                where: { id: activeCourseId },
                select: { title: true, professorId: true, studentId: true }
            });

            if (course) {
                const profId = course.professorId;
                const studentId = course.studentId;
                const courseName = sanitize(course.title, true);
                let folderPath = '';

                // Construct relative folder path if within a subfolder
                if (finalFolderId) {
                    let currentFolder = await prisma.folder.findUnique({ where: { id: finalFolderId } });
                    const pathParts = [];
                    // Traverse up to find all subfolders, stop if parentId is null (meaning it's the root course folder)
                    while (currentFolder && currentFolder.parentId !== null) {
                        pathParts.unshift(sanitize(currentFolder.name));
                        currentFolder = await prisma.folder.findUnique({ where: { id: currentFolder.parentId } });
                    }
                    if (pathParts.length > 0) {
                        folderPath = `/${pathParts.join('/')}`;
                    }
                }

                targetPath = `Teacher_${profId}/Student/Student_${studentId}/${courseName}${folderPath}/${safeName}`;
            } else {
                // Fallback for orphaned courseId?
                targetPath = `Unknown_Course/${safeName}`;
            }

        } else {
            // --- PRIVATE CONTEXT ---
            // Assuming the User is the Teacher/Owner of the private file
            // If Student uploads "Private", it goes to their own Teacher_ID root?
            // "Teacher_{ID}" implies this is keyed by the user's ID if they are a teacher.
            // If user is student, maybe "Student_{ID}"? 
            // The prompt specifically asked for "Teacher_{ID}" structure. 
            // We'll use the uploader's ID as the root.
            const rootPrefix = req.user.role === 'PROF' ? 'Teacher' : 'User';
            const rootId = req.user.id;
            let folderPath = '';

            if (finalFolderId) {
                const folder = await prisma.folder.findUnique({ where: { id: finalFolderId } });
                // If the folder is "Archives" or similar, we include it based on user request:
                // "Private > Archive folder and everything that i put in this folder"
                if (folder) folderPath = `/${sanitize(folder.name)}`;
            }

            targetPath = `${rootPrefix}_${rootId}/Private${folderPath}/${safeName}`;
        }

        const result = await uploadFile(req.file.buffer, targetPath, req.file.mimetype);

        const doc = await prisma.document.create({
            data: {
                title: req.file.originalname,
                type: type || 'OTHER',
                url: result.url,
                size: req.file.size,
                mimeType: req.file.mimetype,
                ownerId,
                courseId: activeCourseId || null,
                sessionId: sessionId || null,
                folderId: finalFolderId || null, // Link to the VFS folder
            },
        });

        res.status(201).json({ document: doc });
    } catch (error) {
        console.error('[Documents] Upload error:', error);
        res.status(500).json({ error: 'Failed to upload document', details: error.message });
    }
});

// GET /api/documents - List documents
router.get('/', authMiddleware, async (req, res) => {
    try {
        const { courseId, sessionId, folderId, type } = req.query;

        // 1. Access Control (User must be Owner OR Student/Prof of the course)
        const accessCondition = {
            OR: [
                { ownerId: req.user.id },
                {
                    course: {
                        OR: [
                            { professorId: req.user.id },
                            { studentId: req.user.id },
                        ],
                    },
                },
            ],
        };

        // 2. Filters
        const filters = [];

        if (folderId) {
            filters.push({ folderId });
        } else {
            // If no folderId provided, we generally want Root items (folderId: null)
            // BUT, for "Private" virtual root, we want ownerId=me, courseId=null, folderId=null
            // This existing route mixes everything.
            // Let's strictly filter by folderId if passed. 
            // If NOT passed, default to folderId: null to prevent flattening the entire drive.
            // Exception: If searching? No search param yet.
            filters.push({ folderId: null });
        }

        if (courseId) filters.push({ courseId });
        if (sessionId) filters.push({ sessionId });
        if (type) filters.push({ type });

        const documents = await prisma.document.findMany({
            where: {
                AND: [
                    accessCondition,
                    ...filters
                ]
            },
            orderBy: { createdAt: 'desc' },
            include: {
                owner: { select: { name: true, role: true } },
            },
        });

        res.json({ documents });
    } catch (error) {
        console.error('[Documents] List error:', error);
        res.status(500).json({ error: 'Failed to list documents' });
    }
});

// GET /api/documents/:id/download
router.get('/:id/download', authMiddleware, async (req, res) => {
    try {
        const doc = await prisma.document.findUnique({
            where: { id: req.params.id },
            include: { course: true },
        });

        if (!doc) {
            return res.status(404).json({ error: 'Document not found' });
        }

        // Check access
        const hasAccess =
            doc.ownerId === req.user.id ||
            doc.course?.professorId === req.user.id ||
            doc.course?.studentId === req.user.id;

        if (!hasAccess) {
            return res.status(403).json({ error: 'Access denied' });
        }

        const urlResult = await getSignedUrl(doc.url.replace('/uploads/', ''));
        res.json({ url: urlResult.url });
    } catch (error) {
        console.error('[Documents] Download error:', error);
        res.status(500).json({ error: 'Failed to get download URL' });
    }
});

// DELETE /api/documents/:id
router.delete('/:id', authMiddleware, async (req, res) => {
    try {
        const doc = await prisma.document.findFirst({
            where: { id: req.params.id, ownerId: req.user.id },
        });

        if (!doc) {
            return res.status(404).json({ error: 'Document not found or access denied' });
        }

        await deleteFile(doc.url.replace('/uploads/', ''));
        await prisma.document.delete({ where: { id: req.params.id } });

        res.json({ success: true });
    } catch (error) {
        console.error('[Documents] Delete error:', error);
        res.status(500).json({ error: 'Failed to delete document' });
    }
});

module.exports = router;
